
version: '2'
services:
    postgres:
        image: postgres:9.6.1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=workix
            - POSTGRES_USER=workix
            - POSTGRES_PASSWORD=workix
            
    wildfly:
        image: mohamnag/wildfly-postgres
        build: .
        ports:
            - "8080:8080"
        environment:
            - DB_NAME=workix
            - DB_PASS=workix
            - DB_USER=workix
            - DB_HOST=postgres
            - DS_NAME=appDS
            - JNDI_NAME=java:jboss/jdbc/workixDS
        depends_on:
            - postgres