version: '2'

services:
  jenkins:
    image: bitnami/jenkins:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - JENKINS_USERNAME=frmichetti
      - JENKINS_PASSWORD=docker
      - DISABLE_JENKINS_INITIALIZATION=yes
    volumes:
      - jenkins_data:/bitnami

volumes:
  jenkins_data:
    driver: local
